# Build stage
ARG DENO_VERSION=2.4.0
FROM app/deno-base:${DENO_VERSION} AS build

# Copy application code
COPY . .

ARG VITE_ENV=prod
ENV VITE_ENV=${VITE_ENV}
RUN deno task web:build

# Production stage with nginx
FROM nginxinc/nginx-unprivileged:stable-alpine
WORKDIR /app
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
COPY --from=build /app/apps/web/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
